"""Add team and game_log models

Revision ID: 65f9bada25c9
Revises: ae24c9788ec6
Create Date: 2026-05-06 19:14:49.669613+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "65f9bada25c9"
down_revision: str | None = "ae24c9788ec6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("career_id", sa.BigInteger(), nullable=False),
        sa.Column("conference", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("primary_color", sa.String(length=7), nullable=False),
        sa.Column("preseason_rating", sa.Float, nullable=False),
        sa.Column("preseason_rank", sa.SmallInteger(), nullable=True),
        sa.Column("current_rating", sa.Float, nullable=False),
        sa.Column("previous_rating", sa.Float, nullable=False),
        sa.Column("current_rank", sa.SmallInteger(), nullable=True),
        sa.Column("previous_rank", sa.SmallInteger(), nullable=True),
        sa.Column("accomplishments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["career_id"],
            ["careers.id"],
            name=op.f("fk_teams_career_id_careers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_index(op.f("ix_teams_career_id"), "teams", ["career_id"], unique=False)
    op.create_table(
        "game_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("career_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("opponent_team_id", sa.BigInteger(), nullable=False),
        sa.Column("location", sa.SmallInteger(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("team_overall", sa.Float, nullable=False),
        sa.Column("opponent_overall", sa.Float, nullable=False),
        sa.Column("team_score", sa.SmallInteger(), nullable=False),
        sa.Column("opponent_score", sa.SmallInteger(), nullable=False),
        sa.Column("overtimes", sa.SmallInteger(), nullable=True),
        sa.Column("team_rank_at_time", sa.SmallInteger(), nullable=True),
        sa.Column("opponent_rank_at_time", sa.SmallInteger(), nullable=True),
        sa.Column("team_rating_at_time", sa.Float, nullable=True),
        sa.Column("opponent_rating_at_time", sa.Float, nullable=True),
        sa.ForeignKeyConstraint(
            ["career_id"],
            ["careers.id"],
            name=op.f("fk_game_logs_career_id_careers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_game_logs_team_id_teams"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_logs")),
    )
    op.create_index(op.f("ix_game_logs_career_id"), "game_logs", ["career_id"], unique=False)
    op.create_index(op.f("ix_game_logs_team_id"), "game_logs", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_logs_team_id"), table_name="game_logs")
    op.drop_index(op.f("ix_game_logs_career_id"), table_name="game_logs")
    op.drop_table("game_logs")
    op.drop_index(op.f("ix_teams_career_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
