"""Add player_stats model

Revision ID: 2b22050b89aa
Revises: 65f9bada25c9
Create Date: 2026-05-06 19:34:02.193558+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2b22050b89aa'
down_revision: str | None = '65f9bada25c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('career_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('scope', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('games_played', sa.SmallInteger(), nullable=False),
    sa.Column('oreb', sa.SmallInteger(), nullable=False),
    sa.Column('dreb', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('steals', sa.SmallInteger(), nullable=False),
    sa.Column('blocks', sa.SmallInteger(), nullable=False),
    sa.Column('turnovers', sa.SmallInteger(), nullable=False),
    sa.Column('fg_made', sa.SmallInteger(), nullable=False),
    sa.Column('fg_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('three_made', sa.SmallInteger(), nullable=False),
    sa.Column('three_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('ft_made', sa.SmallInteger(), nullable=False),
    sa.Column('ft_attempts', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_player_stats_career_id_careers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_stats_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_stats')),
    sa.UniqueConstraint('player_id', 'season', 'scope', name='uq_player_stats_player_season_scope')
    )
    op.create_index(op.f('ix_player_stats_career_id'), 'player_stats', ['career_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_team_id'), 'player_stats', ['team_id'], unique=False)
    op.alter_column('game_logs', 'team_overall',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('game_logs', 'opponent_overall',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('game_logs', 'team_rating_at_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('game_logs', 'opponent_rating_at_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('teams', 'preseason_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('teams', 'current_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('teams', 'previous_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'previous_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('teams', 'current_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('teams', 'preseason_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('game_logs', 'opponent_rating_at_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('game_logs', 'team_rating_at_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('game_logs', 'opponent_overall',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('game_logs', 'team_overall',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_player_stats_team_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_career_id'), table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
