"""Fix data types & add player models

Revision ID: ae24c9788ec6
Revises: ad23a6ed748c
Create Date: 2026-05-05 03:45:09.069750+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ae24c9788ec6'
down_revision: Union[str, None] = 'ad23a6ed748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('career_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('inside_shot', sa.Float(), nullable=False),
    sa.Column('outside_shot', sa.Float(), nullable=False),
    sa.Column('interior_defense', sa.Float(), nullable=False),
    sa.Column('perimeter_defense', sa.Float(), nullable=False),
    sa.Column('athleticism', sa.Float(), nullable=False),
    sa.Column('playmaking', sa.Float(), nullable=False),
    sa.Column('dev_rate', sa.Float(), nullable=False),
    sa.Column('games_played', sa.SmallInteger(), nullable=False),
    sa.Column('is_transferring', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_players_career_id_careers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_index(op.f('ix_players_career_id'), 'players', ['career_id'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('recruits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('career_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('estimated_stars', sa.SmallInteger(), nullable=True),
    sa.Column('dev_rate', sa.Float(), nullable=False),
    sa.Column('inside_shot', sa.Float(), nullable=False),
    sa.Column('outside_shot', sa.Float(), nullable=False),
    sa.Column('interior_defense', sa.Float(), nullable=False),
    sa.Column('perimeter_defense', sa.Float(), nullable=False),
    sa.Column('athleticism', sa.Float(), nullable=False),
    sa.Column('playmaking', sa.Float(), nullable=False),
    sa.Column('scouted', sa.Boolean(), nullable=False),
    sa.Column('committed_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_recruits_career_id_careers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruits'))
    )
    op.create_index(op.f('ix_recruits_career_id'), 'recruits', ['career_id'], unique=False)
    op.add_column('careers', sa.Column('coach_name', sa.String(length=100), nullable=False))
    op.add_column('careers', sa.Column('rng_seed', sa.Integer(), nullable=False))
    op.add_column('careers', sa.Column('current_season', sa.Integer(), nullable=False))
    op.add_column('careers', sa.Column('current_week', sa.Integer(), nullable=False))
    op.add_column('careers', sa.Column('current_team_id', sa.BigInteger(), nullable=False))
    op.add_column('careers', sa.Column('coaching_stints', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('careers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('careers', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('careers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('careers', 'last_played_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('careers', 'last_played_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('careers', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('careers', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('careers', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('careers', 'coaching_stints')
    op.drop_column('careers', 'current_team_id')
    op.drop_column('careers', 'current_week')
    op.drop_column('careers', 'current_season')
    op.drop_column('careers', 'rng_seed')
    op.drop_column('careers', 'coach_name')
    op.drop_index(op.f('ix_recruits_career_id'), table_name='recruits')
    op.drop_table('recruits')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_career_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
